# SIMULATE AND PLOT DATA
# DYLAN MOLINA
# DJMOLINA@EMAIL.ARIZONA.EDU
# 2022-03-15

# SIMULATE PREDICTOR VARIABLE
x <- rnorm(n = 100)
# CALCULATE RESPONSE VARIABLE AND ADD NOISE
y <- x^2 + rnorm(n = 100, sd = 0.2)
# PLOT THE DATA
plot(x = x, y = y)
